
services:
  webcam:
    build:
      context: ./src
      dockerfile: webcam/Dockerfile
    depends_on:
      - control
    volumes:
      - ./log:/app/log

  control:
    build:
      context: ./src
      dockerfile: control/Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./log:/app/log

  segmentor:
    build:
      context: ./src
      dockerfile: segmentor/Dockerfile
    depends_on:
      - control
      - webcam
    volumes:
      - ./log:/app/log

  classifier:
    build:
      context: ./src
      dockerfile: classifier/Dockerfile
    depends_on:
      - control
      - segmentor
    volumes:
      - ./log:/app/log

  robot:
    build:
      context: ./src
      dockerfile: robot/Dockerfile
    depends_on:
      - control
      - classifier
    volumes:
      - ./log:/app/log

  rabbitmq:
    image: "rabbitmq:latest"
    container_name: "rabbitmq"
