[classifier]
mdoel = "gemma3=12b"
prompts = [
    "that there is no hand in the image.",
    "it resembles the OK sign. The thumb and the index finger create an circle while the three other fingers are extended.",
    "it has only the index finger pointing upwards and all the other fingers tucked down. The palm is facing the camera.",
    "it resembles the V sign for victory or for peace. The index and middle finger are extended while the three other fingers are down. The palm is facing the camera.",           
    "it has the index finger, the middle finger and the ring finger extended while the thumb and the pinky are tucked down. The palm is facing the camera.",
    "four fingers besides the thumb are extended. The thumb is tucked down into the middle of the palm and the palm is facing the camera.",
    "all five fingers are extended and separated from each other. The palm is facing the camera."
]

[validator]
model = "gemma3=12b"
prompt = [
    
]

[webcam]
camera_output = ""
preview = true
barrier = 50
init_size = 100
bounding_box = [90,200,128,128]
text_color = [0,255,0]
time_to_cap = 100

[segmentor]
model = "sam2.1_b.pt"
segment_points = [[64,80]]
point_labels = [1]

[robot]
ip = "192.168.125.1"
port = 5000
    [robot.gesture_map]
    hand = {"Class 1" = "right", "Class 3" = "left"}
    mode = {"Class 1" = "move", "Class 3" = "grip"}
        [robot.gesture_map.action]
        "Class 1" = "left"
        "Class 2" = "right"
        "Class 3" = "forward"
        "Class 4" = "backward"
        "Class 5" = "up"
        "Class 6" = "down"