[classifier]
model = "gemma3:12b"
prompts = [
    "There is no hand in the image.",
    "Resembles the OK sign. The thumb and the index finger create a circle while the three other fingers are extended.", #Right
    "Only the index finger points upwards and all the other fingers tucked down.", # Forward
    "Resembles the V sign for victory or for peace. The index and middle finger are extended and apart while the three other fingers are down.", # Left
#    "All five fingers are extended and apart from each other.",
    "The thumb and the index finger forming an L shape while the other fingers are tucked down." , # Left hand
#    "Index finger and the middle finger are extended together upwards. The thumb, ring finger and the pinky are tucked down.",
    "All fingers are extended and together touching each other.  This sign is used to signal 'stop' or 'halt'.", # Close
    "Resembles the 'Live Long and Posper' sign from Star Trek. All five fingers are extended but there is a gap between the middle and the ring finger.", # Open
    #"Resembles the 'horns' sign. Thumb, index finger and the pinky are extended while the middle finger and the ring finger are tucked down.",
    "The fingers are clenched together in to tight fist. This is gesture is used to signal solidarity and defiance.", # Down
    "Resembles the 'shaka' sign where the thumb and the pinky are extended and the three middle fingers tucked.", # Right hand
#    "The hand creates a C-like shape where the thumb and the other fingers are slightly curled and apart from each other.",
#    "The thumb is extended outwards while the other figers are tucked down. ",
    "Thumbs up gesture where the thumb is facing upwards and all other fingers are tucked in.", # Up
    "Middle finger is extended while the other fingers are tucked down. This gesture is considered offensive." # Back
    
]
emoji_prompts = [
    "Not a hand",
    "🤙", # "Shaka or hang loose" #right hand
    "🤘", #left hand
    "✌️", #left
    "👌", #right
    "👆", #forward
    "✊", #backward
    "👍", #up
    "👎", #down
    "✋", #close
    "Live long and prosper", #open
    "🖕", #kill
    # "👊",
    # "🤟", #both
    # "🤘",
]
